### ISSUE TITLE
Support HTML-Like Labels

### ISSUE THREAD

**Issue by k1LoW** [goccy/go-graphviz#14]
Hi @goccy ! 

This is feature request.

I want to use go-graphviz with [HTML-Like Labels](https://www.graphviz.org/doc/info/shapes.html#html).

### DOT

```dot

digraph "testdb" {
  // Config
  graph [rankdir=TB, layout=dot, fontname="Arial"];
  node [shape=record, fontsize=14, margin=0.6, fontname="Arial"];
  edge [fontsize=10, labelfloat=false, splines=none, fontname="Arial"];

  // Tables
  "users" [shape=none, label=<<table border="0" cellborder="1" cellspacing="0" cellpadding="6">
                 <tr><td bgcolor="#EFEFEF"><font face="Arial Bold" point-size="18">users</font> <font color="#666666">[BASE TABLE]</font></td></tr>
                 <tr><td port="id" align="left">id <font color="#666666">[integer]</font></td></tr>
                 <tr><td port="username" align="left">username <font color="#666666">[varchar(50)]</font></td></tr>
                 <tr><td port="password" align="left">password <font color="#666666">[varchar(50)]</font></td></tr>
                 <tr><td port="email" align="left">email <font color="#666666">[varchar(355)]</font></td></tr>
                 <tr><td port="created" align="left">created <font color="#666666">[timestamp without time zone]</font></td></tr>
                 <tr><td port="updated" align="left">updated <font color="#666666">[timestamp without time zone]</font></td></tr>
              </table>>];
}
```

### Render result ( Graphviz 2.40.1 via Homebrew )

![schema](https://user-images.githubusercontent.com/57114/75050357-2c0ad800-550f-11ea-83a3-0fd7cb5a35eb.png)

### goccy/go-graphviz/cmd/dot v1.3.1 result

```console
$ cat schema.dot | ~/path/to/go-graphviz/cmd/dot -Tpng -o schema.png # error
Not built with libexpat. Table formatting is not available.
in label of node users

```

Thank you for a very good library !!

**Comment by goccy** [comment]
Thanks for the reporting !

I fixed this issue with #15 , and released as v0.0.2 ( https://github.com/goccy/go-graphviz/releases/tag/v0.0.2 )

**Comment by k1LoW** [comment]
GREAT!!! QUICK!!! THANK YOU!!!

**Comment by goccy** [comment]
Sorry, I noticed that there was a bug in the text layout, so fix it with #16

**Comment by k1LoW** [comment]
@goccy OK! Thank you !!!!!

**Comment by 201403780** [comment]
Hi, could you give an example of this, can't figure it out. i get the html string every time.

thanks in advance.

**Comment by qomosoloto** [comment]
> Hi, could you give an example of this, can't figure it out. i get the html string every time.
> 
> Here is what i'm doing:
> `n, err := graph.CreateNode("n") if err != nil { log.Fatalln(err) } n.SetShape("none") n.Set("label", "<<TABLE><TR><TD>Tamano</TD><TD>123</TD></TR></TABLE>>") `
> 
> made it work, thanks!
> Great tool!

I also got the html string every time....Have you solved this?

**Comment by k1LoW** [comment]
> Hi, could you give an example of this, can't figure it out. 

I always generate a graph from a dot file, as in the example given in https://github.com/goccy/go-graphviz/issues/14#issue-569045848.

For an example of generating a graph from a dot file, see [cmd/dot.go](https://github.com/goccy/go-graphviz/blob/master/cmd/dot/dot.go).

**Comment by guillotjulien** [comment]
Looks like go-graphviz always quotes labels (`label="<<TABLE><TR><TD>Tamano</TD><TD>123</TD></TR></TABLE>>",` instead of `label=<<TABLE><TR><TD>Tamano</TD><TD>123</TD></TR></TABLE>>,`) resulting in Graphviz rendering the label as a string.

It can be reproduced on the playground like that:
```
digraph "" {
  // Config
  graph [layout=dot, fontname="Arial"];
  node [fontsize=14, margin=0.6, fontname="Arial"];
  edge [fontsize=10, labelfloat=false, splines=none, fontname="Arial"];

  test1 [shape=plaintext, label=<<TABLE><TR><TD>Tamano</TD><TD>123</TD></TR></TABLE>>];

  test2 [shape=plaintext, label="<<TABLE><TR><TD>Tamano</TD><TD>123</TD></TR></TABLE>>"];
}
```

**Comment by miluChen** [comment]
Look at here https://github.com/goccy/go-graphviz/issues/23#issuecomment-716222165 👍
