### ISSUE TITLE
In Windows 'go get' the library fails

### ISSUE THREAD

**Issue by leonj1** [goccy/go-graphviz#27]
Not sure why this is happening, but in Windows 10, performing the 'go get' operation returns the below result.
The package fails to download.

```
go get "github.com/goccy/go-graphviz"
# github.com/goccy/go-graphviz/internal/ccall
In file included from common.c:5:0:
common/emit.c: In function 'selectedLayer':
common/emit.c:31:18: warning: implicit declaration of function 'strtok_s' [-Wimplicit-function-declaration]
 #define strtok_r strtok_s
                  ^
common/emit.c:1061:38: note: in expansion of macro 'strtok_r'
     while ((rval == FALSE) && (cur = strtok_r(part_in_p, gvc->layerListDelims, &buf_part_p))) {
                                      ^
common/emit.c:1061:36: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
     while ((rval == FALSE) && (cur = strtok_r(part_in_p, gvc->layerListDelims, &buf_part_p))) {
                                    ^
common/emit.c:1062:10: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  w1 = w0 = strtok_r (cur, gvc->layerDelims, &buf_p);
          ^
common/emit.c:1064:9: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
      w1 = strtok_r (NULL, gvc->layerDelims, &buf_p);
         ^
```

**Comment by alexZaicev** [comment]
haven`t experienced this issue on my machine running Windows 10. Maybe some more details would help, like env info etc.

**Comment by goccy** [comment]
No response, so I close this

**Comment by nervmor** [comment]
> @goccy It seems I ran into the same issue, see [my post here](https://github.com/EwenQuim/renpy-graphviz/issues/54#issuecomment-2118021801) and pasted below the output
> 
> ```
> E:\Programs64\Dev\Go\bin\GraphViz>..\go build -o my-renpy-graphviz-executable
> go: downloading github.com/skratchdot/open-golang v0.0.0-20200116055534-eef842397966
> go: downloading github.com/fatih/color v1.16.0
> go: downloading github.com/goccy/go-graphviz v0.1.2
> go: downloading github.com/emicklei/dot v1.6.2
> go: downloading github.com/pelletier/go-toml v1.9.5
> go: downloading github.com/mattn/go-colorable v0.1.13
> go: downloading github.com/mattn/go-isatty v0.0.20
> go: downloading golang.org/x/sys v0.18.0
> go: downloading golang.org/x/image v0.14.0
> go: downloading github.com/golang/freetype v0.0.0-20170609003504-e2365dfdc4a0
> go: downloading github.com/fogleman/gg v1.3.0
> go: downloading github.com/pkg/errors v0.9.1
> package pkg.amethysts.studio/renpy-graphviz
>         imports github.com/goccy/go-graphviz
>         imports github.com/goccy/go-graphviz/cgraph
>         imports github.com/goccy/go-graphviz/internal/ccall: build constraints exclude all Go files in C:\Users\FaceCrap\go\pkg\mod\github.com\goccy\go-graphviz@v0.1.2\internal\ccall
> ```
> 
> go install just repeated the last bit and still no exe anywhere on my system.
> 
> ```
> package pkg.amethysts.studio/renpy-graphviz
>         imports github.com/goccy/go-graphviz
>         imports github.com/goccy/go-graphviz/cgraph
>         imports github.com/goccy/go-graphviz/internal/ccall: build constraints exclude all Go files in C:\Users\FaceCrap\go\pkg\mod\github.com\goccy\go-graphviz@v0.1.2\internal\ccall
> ```

I had the same problem
