### ISSUE TITLE
Example linker error (macOS) 

### ISSUE THREAD

**Issue by Micrified** [goccy/go-graphviz#35]
Amazing package Masaaki! However, I cannot seem to compile your example application after following the installation commands. It fails at the linking stage, with the following error: 

`/usr/local/go/pkg/tool/darwin_amd64/link: /usr/local/go/pkg/tool/darwin_amd64/link: combining dwarf failed: Unknown load command 0x32 (50)`

I am running MacOS 10.15.7, with go1.10 darwin/amd64

**Comment by goccy** [comment]
Can you give me some more specific information needed to reproduce it?

**Comment by Micrified** [comment]
@goccy Hello, 

Some days ago I reinstalled my Operating System. When I now try to compile your examples, it works! I think you can close this issue, as I am not able to reproduce it. 

Thank you!
