### ISSUE TITLE
Can this render the image in pure Go?

### ISSUE THREAD

**Issue by dougwatson** [goccy/go-graphviz#36]
I see a lot of CGO in the code, but the Readme says "Supports rendering graph in pure Go".

Is there a way to build this without CGO cause I get this error when trying it:

go-graphviz$ CGO_ENABLED=0 go build
package github.com/goccy/go-graphviz
	imports github.com/goccy/go-graphviz/cgraph
	imports github.com/goccy/go-graphviz/internal/ccall: build constraints exclude all Go files in GOPATH/src/github.com/goccy/go-graphviz/internal/ccall 

(but builds fine if I set CGO_ENABLED=1)

**Comment by goccy** [comment]
`go-graphviz` is implemented as a hybrid of cgo and pure Go. 
`CGO_ENABLED=1` is required because it utilizes graphviz's C library for the layout of graphs.
On the other hand, graph rendering is done with pure Go.

**Comment by xhit** [comment]
In the readme should have a notice "Require CGO" because:

* Cannot be cross compiled.
* Is not pure go because use CGO, if a little part of code requires C code, is not pure Go.
