### ISSUE TITLE
Environment to generate imagehash.json

### ISSUE THREAD

**Issue by k1LoW** [goccy/go-graphviz#40]
Hi, @goccy !!!

Can you share what environment you are generating imagehash.json from?

- OS
- How to get Graphviz binary or source code ( https://gitlab.com/graphviz/graphviz does not have `2.40.1` tag )
- etc.

https://github.com/goccy/go-graphviz/blob/1f0a44108c1d533c39ac8cc2b4a7b08a6fb43858/compatible_test.go#L76

I'm looking to expand the scope of testing for compatible_test.go.
For this purpose, I need to know the environment to generate imagehash.json.

**Comment by goccy** [comment]
Oh, sorry for the confusion ...
I'm using `dot` from `graphviz version 2.44.1 (20200629.0846)` ( installed by `homebrew` ).

**Comment by k1LoW** [comment]
Thank you!!!
