### ISSUE TITLE
support setAttr fontname

### ISSUE THREAD

**Issue by hehuilei** [goccy/go-graphviz#58]
like this:
func (n *Node) SetFontName(name string) *Node {
	n.SafeSet(string(fontNameAttr), name, "")
	return n
}

![image](https://user-images.githubusercontent.com/10290801/168828281-c310ab0d-98b4-445a-abb6-ea34601522a2.png)

**Comment by goccy** [comment]
I've released this feature with v0.2.0. Thank you.
