### ISSUE TITLE
Can't create two edges between two nodes

### ISSUE THREAD

**Issue by Dared3vi1** [goccy/go-graphviz#61]
## Short description
I can't create two edges between two nodes. (two from node a to b).
![graph](https://user-images.githubusercontent.com/75643431/186904711-68e1ffe2-e2f0-40c6-b870-57880e40d986.png)
Second edge replaces the first one.
## Code example

<details>
  <summary>Go code</summary>

```go
g := graphviz.New()
graph, err := g.Graph()
n, err := graph.CreateNode("n")
if err != nil {
	log.Err(err.Error())
}
m, err := graph.CreateNode("m")
if err != nil {
	log.Err(err.Error())
}
e, err := graph.CreateEdge("e", n, m)
if err != nil {
	log.Err(err.Error())
}
e.SetLabel("e")
f, err := graph.CreateEdge("f", n, m)
if err != nil {
	log.Err(err.Error())
}
f.SetLabel("f")
var buf bytes.Buffer
if err := g.Render(graph, "dot", &buf); err != nil {
	log.Err(err.Error())
}
```
</details>

<details>
  <summary>Dot output</summary>

```
digraph "" {
	graph [bb="0,0,54,124.8"];
	node [label="\N"];
	n	 [height=0.5,
		pos="27,106.8",
		width=0.75];
	m	 [height=0.5,
		pos="27,18",
		width=0.75];
	n -> m [key=e,
	label=f,
	lp="29.33,62.4",
	pos="e,27,36.072 27,88.401 27,76.295 27,60.208 27,46.467"];
}
```
  
</details>

<details>
  <summary>Generated graph</summary>

![Screenshot](https://user-images.githubusercontent.com/75643431/186908363-bff30006-111b-4f12-baeb-05a5b2f1ac93.png)
  
</details>

**Comment by denk0403** [comment]
I'm not sure if this has already been fixed, but I can't reproduce this issue anymore; both edges are present in the output.

**Comment by goccy** [comment]
Thank you, Maybe this problem was fixed.
