### ISSUE TITLE
Graphviz built without any triangulation library

### ISSUE THREAD

**Issue by Btijmen** [goccy/go-graphviz#65]
Using 

```
g := graphviz.New()
	graph, err := g.Graph()
	graph.SetLayout("fdp") 
	graph.SetOverlap(false)
```

And rendering to svg

```
	var buf bytes.Buffer
	if err := g.Render(graph, graphviz.SVG, &buf); err != nil {
	log.Fatal(err)
	}
	_, err = g.RenderImage(graph)
	if err != nil {
	log.Fatal(err)
	}
	if err := g.RenderFilename(graph, graphviz.SVG, "mygraph.svg"); err != nil {
	log.Fatal(err)
	}
```

Results in an error `2023/02/07 10:51:52 delaunay_tri: Graphviz built without any triangulation library`

I'm running MacOS Ventura 13.1, fully updated. GTS is installed 

```
brew list --versions gts
gts 0.7.6_2
```

Since graphviz is packaged with go-graphviz, I'm guessing it probably has to be built with gts?

**Comment by goccy** [comment]
This issue has likely been resolved. If you're still encountering any problems, please let me know.
