### ISSUE TITLE
How to Change Rendered Image Resolution?

### ISSUE THREAD

**Issue by Sett17** [goccy/go-graphviz#67]
I am currently using the RenderImage function. However, the resolution of the resulting image is too low for my needs. Is there any way to change the resolution of the rendered image using the RenderImage function?

**Comment by denk0403** [comment]
You can adjust the render resolution by setting the ["dpi" attribute](https://graphviz.org/docs/attrs/dpi/) on the graph . For example, the equivalent DOT syntax would be:
```dot
graph test { dpi = 182; a -- b; ... }
```
