### ISSUE TITLE
C2x

### ISSUE THREAD

**Issue by vicky-sukarma** [goccy/go-graphviz#72]
vendor/github.com/goccy/go-graphviz/internal/ccall/dotgen/dotsplines.c:2310:13: warning: a function declaration without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]

occur in mac os 13.3 and go version 1.18

**Comment by ringods** [comment]
The project I'm using this library on worked around a month ago, but not anymore due to this error. Is there any workaround?

**Comment by davidovich** [comment]
I believe that the pg_query_go project had the same [issue](https://github.com/pganalyze/pg_query_go/issues/81), with a seemingly simple [fix](https://github.com/pganalyze/pg_query_go/pull/83/files).
