### ISSUE TITLE
Build a tree where nodes are not grouped by name

### ISSUE THREAD

**Issue by naueramant** [goccy/go-graphviz#87]
So I have a usecase where I want to build a tree structure, but some nodes are named the same. I can't seem to find a way to disable the grouping of nodes named the same thing.

Any suggestions?

**Comment by DanielRasho** [comment]
Same issue here

**Comment by goccy** [comment]
@naueramant  This library respects the behavior of the original Graphviz library. Therefore, if something is possible with the original library, it can be achieved in the same way with this library.

**Comment by naueramant** [comment]
Guess we can close this one. Ended up just adding a unique id for all nodes and set it's label like so:
```go
id := uuid.New().String()
childNode, _ := graph.CreateNode(id)
childNode.SetLabel("some label")
```
Maybe not the best way to do it though but was fine for my use-case.
